"""make all content fields nullable for incremental creation

Revision ID: 07a5bf02562f
Revises: d5fb0355511d
Create Date: 2026-09-11 13:12:56.178330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a5bf02562f'
down_revision: Union[str, Sequence[str], None] = 'd5fb0355511d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Trade or generic pharmaceutical product name')
    op.alter_column('complaints', 'batch_lot_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Batch / Lot manufacturing identification number')
    op.alter_column('complaints', 'complaint_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Categorization: Contamination, Packaging, Potency, Labeling, Dissolution, etc.')
    op.alter_column('complaints', 'complaint_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='Date the complaint was officially lodged')
    op.alter_column('complaints', 'detailed_description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Detailed narrative describing the observed issue or defect')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'detailed_description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Detailed narrative describing the observed issue or defect')
    op.alter_column('complaints', 'complaint_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='Date the complaint was officially lodged')
    op.alter_column('complaints', 'complaint_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Categorization: Contamination, Packaging, Potency, Labeling, Dissolution, etc.')
    op.alter_column('complaints', 'batch_lot_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Batch / Lot manufacturing identification number')
    op.alter_column('complaints', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Trade or generic pharmaceutical product name')
    # ### end Alembic commands ###
