"""create complaints table

Revision ID: d5fb0355511d
Revises: 
Create Date: 2026-09-11 13:06:15.843930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fb0355511d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_source', sa.String(length=100), nullable=True, comment='Source of complaint: Hospital, Pharmacy, Distributor, Patient, Regulatory'),
    sa.Column('customer_name', sa.String(length=255), nullable=True, comment='Customer or institution reporting the issue'),
    sa.Column('product_name', sa.String(length=255), nullable=False, comment='Trade or generic pharmaceutical product name'),
    sa.Column('product_strength_grade', sa.String(length=100), nullable=True, comment='Dosage strength (e.g. 500mg) or chemical grade (e.g. USP/Ph. Eur)'),
    sa.Column('batch_lot_number', sa.String(length=100), nullable=False, comment='Batch / Lot manufacturing identification number'),
    sa.Column('manufacturing_date', sa.Date(), nullable=True, comment='Batch manufacturing date'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='Batch expiration or re-test date'),
    sa.Column('quantity_affected', sa.Numeric(precision=12, scale=2), nullable=True, comment='Quantity of units or mass affected'),
    sa.Column('quantity_unit', sa.String(length=50), nullable=True, comment='Unit of measure (e.g., vials, tablets, kg, bottles)'),
    sa.Column('complaint_type', sa.String(length=100), nullable=False, comment='Categorization: Contamination, Packaging, Potency, Labeling, Dissolution, etc.'),
    sa.Column('complaint_date', sa.Date(), nullable=False, comment='Date the complaint was officially lodged'),
    sa.Column('detailed_description', sa.Text(), nullable=False, comment='Detailed narrative describing the observed issue or defect'),
    sa.Column('initial_severity', sa.String(length=50), nullable=True, comment='QA Initial Severity: Critical, Major, Minor'),
    sa.Column('priority', sa.String(length=50), nullable=True, comment='Investigation priority: High, Medium, Low'),
    sa.Column('risk_classification', sa.String(length=50), nullable=True, comment='Regulatory Risk: Class I (Life-threatening), Class II (Temporary), Class III (Minor)'),
    sa.Column('recommended_action', sa.Text(), nullable=True, comment='Recommended QA action (CAPA, Quarantine, Stability, Recall)'),
    sa.Column('ai_reasoning_notes', sa.Text(), nullable=True, comment='AI agent root cause hypothesis and QA triage rationale'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_batch_lot_number'), 'complaints', ['batch_lot_number'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_type'), 'complaints', ['complaint_type'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_product_name'), 'complaints', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_product_name'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_type'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_batch_lot_number'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
